plugins:
  vivokey_openid_enabled:
    default: false
  vivokey_openid_registration:
    default: false
  vivokey_openid_client_id:
    default: ""
  vivokey_openid_client_secret:
    default: ""
  vivokey_openid_allow_connect:
    default: true
  vivokey_openid_allow_disconnect:
    default: false
  vivokey_openid_verbose_logging:
    default: false
  vivokey_openid_token_scope:
    default: ""
  vivokey_openid_error_redirects:
    default: ''
    type: list
    list_type: secret
