plugins:
  vivokey_openid_enabled:
    default: false
  vivokey_openid_discovery_document:
    default: ""
  vivokey_openid_client_id:
    default: ""
  vivokey_openid_client_secret:
    default: ""
  vivokey_openid_allow_association_change:
    default: false
  vivokey_openid_authorize_scope:
    default: "openid"
  vivokey_openid_verbose_logging:
    default: false
  vivokey_openid_token_scope:
    default: ""
  vivokey_openid_error_redirects:
    default: ''
    type: list
    list_type: secret
